const customStyles = {
  fontFamily: 'Helvetica, sans-serif',
  gradientStart: '#36373b',
  gradientMid: '#a1aeb8',
  gradientEnd: '#040405',
  locationFontColor: '#382929',
  todayTempFontColor: '#2b1919',
  todayDateFontColor: '#11171a',
  todayRangeFontColor: '#B5DEF4',
  todayDescFontColor: '#B5DEF4',
  todayInfoFontColor: '#1c3b4e',
  todayIconColor: '#FFF',
  forecastBackgroundColor: '#FFF',
  forecastSeparatorColor: '#DDD',
  forecastDateColor: '#777',
  forecastDescColor: '#777',
  forecastRangeColor: '#777',
  forecastIconColor: '#4BC4F7',
};
export default customStyles;
